version: '2'
services:
  web:
    extends:
      file: ../common-services.yml
      service: web
    volumes:
      - "../../:/pycroft"
    # A service being extended may have no links.
    links:
      - db:db
    ports:
      - 5001:5000
  db:
    extends:
      file: ../common-services.yml
      service: db
    volumes:
      - "pycroft_postgres:/var/lib/postgresql/data"
      - "../../:/pycroft"

volumes:
  pycroft_postgres:
