language: python
sudo: required
dist: trusty

cache:
  directories:
    - /var/lib/docker/image

services:
  - docker

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  - "docker version"
  - "docker-compose version"

script:
  - export DOCKER_COMPOSE="docker-compose -f docker-compose-travis.yml"
  - $DOCKER_COMPOSE build
  - $DOCKER_COMPOSE up -d
  - $DOCKER_COMPOSE run --rm -u root web sh -c 'pip3 install coverage && su pycroft -c "nosetests --with-xunit --with-coverage --cover-erase --cover-branches --cover-package=web,pycroft,legacy"'
