version: '2'
services:
  web:
    extends:
      file: docker-compose.bare.yml
      service: web
    # A service being extended may have no links.
    links:
      - db:db
      - ldap:ldap
  db:
    extends:
      file: docker-compose.bare.yml
      service: db
  ldap:
    extends:
      file: docker-compose.bare.yml
      service: ldap
