version: '2'
services:
  web:
    extends:
      file: docker-compose.bare.yml
      service: web
    volumes:
      - ./:/pycroft
    # A service being extended may have no links.
    links:
      - db:db
      - ldap:ldap
    ports:
      - 5001:5000
  db:
    extends:
      file: docker-compose.bare.yml
      service: db
    volumes:
      - "pycroft_postgres:/var/lib/postgresql/data"
  ldap:
    extends:
      file: docker-compose.bare.yml
      service: ldap

volumes:
  pycroft_postgres:
