version: '2'
services:
  web:
    extends:
      file: docker-compose.bare.yml
      service: web
    volumes:
      - ./:/pycroft
  db:
    extends:
      file: docker-compose.bare.yml
      service: web
