version: '2'
services:
  web:
    # this container will run our tests
    extends:
      file: docker-compose.travis.yml
      service: web
    volumes:
      - ./:/pycroft
    links:
      - db:db
      - ldap:ldap
      - rabbitmq:rabbitmq
  dummy_worker:
    extends:
      file: docker-compose.bare.yml
      service: dummy_worker
    volumes:
      - ./:/pycroft
    links:
      - rabbitmq:rabbitmq
  db:
    extends:
      file: docker-compose-travis.yml  # not using `bare` b/c we want to have the tmpfs
      service: db
  ldap:
    extends:
      file: docker-compose.bare.yml
      service: ldap
  rabbitmq:
    extends:
      file: docker-compose.bare.yml
      service: rabbitmq
