version: '2'
services:
  web:
    extends:
      file: common-services.2.yml
      service: web_base
  # testing variants of `web`
  web_testing:
    extends:
      file: common-services.2.yml
      service: web_base
    command: "/bin/true"
    environment:
      - HADES_BROKER_URI=amqp://celery:celery@rabbitmq:5672/
      - HADES_RESULT_BACKEND_URI=rpc://celery:celery@rabbitmq:5672/
      - PYCROFT_LDAP_HOST=ldap
      - PYCROFT_LDAP_PORT=389
      - PYCROFT_LDAP_BIND_DN=cn=admin,dc=agdsn,dc=de
      - PYCROFT_LDAP_BIND_PW=password
      - PYCROFT_LDAP_BASE_DN=ou=pycroft,dc=agdsn,dc=de
  dummy_worker:  # a dummy worker mocking hades for testing the client
    build:
      context: ..
    command: "sh -c 'cd helpers && celery -A dummy_celery_worker worker --loglevel=info'"
    environment:
      - TEST_HADES_BROKER_URI=amqp://celery:celery@rabbitmq:5672/
      - TEST_HADES_RESULT_BACKEND_URI=rpc://celery:celery@rabbitmq:5672/
  db:
    extends:
      file: common-services.2.yml
      service: db_base
  db_optimized:
    extends:
      file: common-services.2.yml
      service: db_base
    environment:
      - PGDATA=/postgres
    tmpfs:
      - /postgres
  ldap:
    image: dinkel/openldap
    environment:
      - SLAPD_PASSWORD=password
      - SLAPD_DOMAIN=agdsn.de
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=celery
      - RABBITMQ_DEFAULT_PASS=celery
